[project]
name = "vibe-lights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.2",
    "requests>=2.32.4",
    "sounddevice>=0.5.2",
    "tinytuya>=1.17.3",
    "websockets>=15.0.1",
]
